version: 2

models:
  - name: sales
    description: sales table
    tests:
      - unique:
          column_name: "(orders_id || '-' || products_id)"

    columns:
      - name: orders_id
        description: orders id by unique order
        tests:
          - not_null

      - name: products_id
        description: list of product id
        tests:
          - not_null

      - name: qty

      - name: turnover
        description: revenue
        tests:
          - not_null

      - name: purchase_cost
        description: price of purchase
        tests:
          - not_null

      - name: margin
        description: margin of the sales
